print("Read me 5 numbers:")
print("n1:")
n1 = int(input())
print("n2:")
n2 = int(input())
print("n3:")
n3 = int(input())
print("n4:")
n4 = int(input())
print("n5:")
n5 = int(input())
print("avg:" + str((n1 + n2 + n3 + n4 + n5) / 5))
