print("Read me 5 numbers:")
print("n1:")
n = int(input())
print("n2:")
n += int(input())
print("n3:")
n += int(input())
print("n4:")
n += int(input())
print("n5:")
n += int(input())
print("avg:" + str(n / 5))
